data:
  class_path: aerial_image_cls.data.aerial_image.AerialImageDataset
  init_args:
    root_path: data/250mjs
    labels: [0, 5, 10, 30, 40, 80, 90]
    train_batch_size: 128
    val_batch_size: 128
    num_workers: 8

model:
  class_path: aerial_image_cls.models.FCDenseNet
  init_args:
    model_name: densenet121
    num_classes: 7
    learning_rate: 0.001
    max_epochs: 60

trainer:
  max_epochs: 60
  accelerator: "gpu"
  devices: 1
  precision: 32

  callbacks:
    - class_path: RichProgressBar
      init_args:
        leave: True
    - class_path: ModelCheckpoint
      init_args:
        filename: "epoch_{epoch:03d}_acc_{val/acc:.02f}"
        auto_insert_metric_name: False
        save_top_k: -1
        every_n_epochs: 5
    - LearningRateMonitor

seed_everything: 23333
